### ISSUE TITLE
Sum of timers for complex task

### ISSUE THREAD

**Issue by PrzemekPopowicz** [autyzm-pg/friendly-plans-react#213] opened 2019-10-28 08:45 UTC
https://xd.adobe.com/spec/01d5ebeb-d8a4-4a08-7f23-309931817948-77e4/screen/16221958-279a-48ff-ab0b-8ec58508ffbd/Zadanie-Z-o-one

![image](https://user-images.githubusercontent.com/9513577/67664243-8a5fe980-f967-11e9-8736-4a1030a1c13e.png)

AC:
- Display a sum of timers of each of subtasks for a complex task

**Comment by mikolevy** [comment] 2020-02-02 17:49
Duplicate of #249

**Closed by mikolevy** 2020-02-02 17:49 UTC
Labels: Task View, Teacher mode
